version: 0.0
os: linux
files:
  - source: /
    destination: /opt/codepipeline-test
hooks:
  ApplicationStop:
    - location: infra/codedeploy/applicationStop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: infra/codedeploy/beforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: infra/codedeploy/afterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: infra/codedeploy/applicationStart.sh
      timeout: 300
      runas: root
